spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: customers-route
              uri: lb://tech-test-spring
              predicates:
                - Path=/v1/api/customers/**

            - id: accounts-route
              uri: lb://tech-test-spring-2
              predicates:
                - Path=/v1/api/accounts/**

            - id: movements-route
              uri: lb://tech-test-spring-2
              predicates:
                - Path=/v1/api/movements/**             
server:
  port: 8009
management:
  endpoint:
    health:
      show-details: always
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: health,gateway
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
                