spring:
  application:
    name: tech-test-spring-2
  r2dbc:
    url: r2dbc:mysql://localhost:3306/pichincha_interv
    username: alpha
    password: Admin.123
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8081

app:
  kafka:
    topic:
      cliente-topic: cliente-topic      

eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    health:
      show-details: always    
  endpoints:
    web:
      exposure:
        include: health,gateway