spring:
  application:
    name: tech-test-spring
  r2dbc:
    url: ${SPRING_DATA_MYSQL_URL} 
    username: ${SPRING_DATA_MYSQL_USERNAME}
    password: ${SPRING_DATA_MYSQL_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
server:
  port: 8080
app:
  kafka:
    topic:
      cliente-topic: cliente-topic
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
management:
  endpoint:
    health:
      show-details: always    
  endpoints:
    web:
      exposure:
        include: health,gateway